In [36]:
import pandas as pd

cpu_img = pd.read_csv("cpu_img.csv")
gpu_img = pd.read_csv("gpu_img.csv")
ssd_img = pd.read_csv("ssd_img.csv")
ram_img = pd.read_csv("ram_img.csv")
hdd_img = pd.read_csv("hdd_img.csv")

merged_df = pd.concat([cpu_img, gpu_img, ssd_img, ram_img, hdd_img], axis=0, ignore_index=True)
merged_df.to_csv("product_image.csv", index=False, encoding="utf-8-sig")

In [35]:
cpu_product = pd.read_csv("cpu_product.csv")
gpu_product = pd.read_csv("gpu_product.csv")
ssd_product = pd.read_csv("ssd_product.csv")
ram_product = pd.read_csv("ram_product.csv")
hdd_product = pd.read_csv("hdd_product.csv")

merged_df = pd.concat([cpu_product, gpu_product, ssd_product, ram_product, hdd_product], axis=0, ignore_index=True)

import numpy as np
# '가격비교예정'을 NaN으로 대체
merged_df['price'] = merged_df['price'].replace('가격비교예정', np.nan)

# 쉼표 제거 후 '원'을 기준으로 분리하고 float로 변환
merged_df['price'] = merged_df['price'].str.split('원').str[0].astype(float)

merged_df.to_csv("product.csv", index=False, encoding="utf-8-sig")

In [10]:
len(merged_df)

4186

In [26]:
import numpy as np
# '가격비교예정'을 NaN으로 대체
merged_df['price'] = merged_df['price'].replace('가격비교예정', np.nan)

# 쉼표 제거 후 '원'을 기준으로 분리하고 float로 변환
merged_df['price'] = merged_df['price'].str.split('원').str[0].astype(float)

In [29]:
merged_df.to_csv("product.csv")

In [1]:
import pandas as pd
import numpy as np
# 데이터 생성을 위한 설정
num_reviews = 100000
user_idx_range = range(1, 30001)  # 1~4000
product_idx_range = range(1, 4187)  # 1~4186
rating_range = range(1, 6)  # 1~5

# 랜덤 데이터 생성
np.random.seed(42)  # 재현 가능성을 위해 시드 설정
data = {
    'review_idx': range(1, 100001),
    'user_idx': np.random.choice(user_idx_range, size=num_reviews),
    'product_idx': np.random.choice(product_idx_range, size=num_reviews),
    'review_rating': np.random.choice(rating_range, size=num_reviews)
}

# DataFrame 생성
df = pd.DataFrame(data)

# 결과 확인
print(df.head())
print(f"데이터 크기: {df.shape}")
print(f"데이터 타입:\n{df.dtypes}")

   review_idx  user_idx  product_idx  review_rating
0           1     23655         2602              2
1           2     15796         3405              1
2           3       861         1690              4
3           4      5391         3953              5
4           5     29803         1336              3
데이터 크기: (100000, 4)
데이터 타입:
review_idx       int64
user_idx         int64
product_idx      int64
review_rating    int64
dtype: object


In [4]:
df.head().to_csv("rating_sample.csv", index=False, encoding="utf-8-sig")

In [2]:
df.loc[df['user_idx'] == 4003]

review_idx  user_idx  product_idx  review_rating
9604         9605      4003         3465              4
39680       39681      4003          449              2
81366       81367      4003         1013              5

In [3]:
df.to_csv("test_rating.csv", index=False, encoding="utf-8-sig")

In [3]:
# 2. User-Item Matrix 생성
user_item_matrix = df.pivot_table(index='user_idx', columns='product_idx', values='review_rating')
user_item_matrix = user_item_matrix.fillna(0)  # 결측값 0으로 채움

In [23]:
user_item_matrix

product_idx  1     2     3     4     5     6     7     8     9     10    ...  \
user_idx                                                                 ...   
1             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
2             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
3             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
5             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
...           ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
29996         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
29997         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
29998         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
29999         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
30000         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   

product_idx  4177  4178  4179  4180  4181  4182  4183  4184  4185  4186  
user_idx                                                                 
1             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...           ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
29996         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
29997         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
29998         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
29999         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
30000         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[28921 rows x 4186 columns]

In [24]:
user_idx_list = user_item_matrix.index
user_idx_list

Index([    1,     2,     3,     4,     5,     6,     7,     8,     9,    10,
       ...
       29991, 29992, 29993, 29994, 29995, 29996, 29997, 29998, 29999, 30000],
      dtype='int64', name='user_idx', length=28921)

In [25]:
item_idx_list = user_item_matrix.columns
item_idx_list

Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       ...
       4177, 4178, 4179, 4180, 4181, 4182, 4183, 4184, 4185, 4186],
      dtype='int64', name='product_idx', length=4186)

In [19]:
from sklearn.decomposition import SparsePCA
sparse_pca = SparsePCA(n_components=100, random_state=42)
user_sparse_pca = sparse_pca.fit_transform(user_item_matrix)
user_sparse_pca

array([[-0.00497819, -0.00479733, -0.00477409, ..., -0.00420614,
        -0.00486943, -0.00390836],
       [-0.00497819, -0.00479733, -0.00477409, ..., -0.00420614,
        -0.00486943, -0.00390836],
       [-0.00497819, -0.00479733, -0.00477409, ..., -0.00420614,
        -0.00486943, -0.00390836],
       ...,
       [-0.00497819, -0.00479733, -0.00477409, ..., -0.00420614,
        -0.00486943, -0.00390821],
       [-0.00497819, -0.00479733, -0.00477409, ..., -0.00420614,
        -0.00486943, -0.00390836],
       [-0.00497819, -0.00479733, -0.00477409, ..., -0.00420614,
        -0.00486943, -0.00390836]], shape=(28921, 100))

In [21]:
from sklearn.decomposition import SparsePCA
import numpy as np

# 밀집행렬 (user_item_matrix) 가정 (SparsePCA는 희소행렬 직접 지원 안 함)
X = user_item_matrix.values  # 희소행렬을 밀집행렬로 변환
V = sparse_pca.components_.T  # 희소 주성분 (m × k)

# 재구성된 데이터
X_reconstructed = np.dot(user_sparse_pca, V.T)  # X ≈ Z V^T

# Frobenius Norm 계산
frobenius_norm = np.sqrt(np.sum(X ** 2))  # ||X||_F
reconstruction_error = np.sqrt(np.sum((X - X_reconstructed) ** 2))  # ||X - X̂||_F

# 설명된 분산 비율 추정
explained_variance_ratio = 1 - (reconstruction_error ** 2 / frobenius_norm ** 2)
print(f"Approximate explained variance ratio: {explained_variance_ratio:.4f}")

Approximate explained variance ratio: 0.0409


In [12]:
from scipy.sparse import csr_matrix
user_matrix_sparse = csr_matrix(user_item_matrix.values)  # 희소행렬로 변환
user_matrix_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 99962 stored elements and shape (28921, 4186)>

In [10]:
from scipy.sparse import csr_matrix
item_matrix_sparse = csr_matrix(user_item_matrix.T.values)  # 희소행렬로 변환
item_matrix_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 99962 stored elements and shape (4186, 28921)>

In [22]:
from sklearn.decomposition import TruncatedSVD
# 희소행렬 (user_item_matrix_sparse) 가정
svd = TruncatedSVD(n_components=100, random_state=42)
svd.fit(user_matrix_sparse)

# Explained variance ratio
explained_variance = svd.explained_variance_ratio_
cumulative_variance = np.cumsum(explained_variance)

# 누적 분산 비율 출력
print("Cumulative explained variance ratio:", cumulative_variance)

Cumulative explained variance ratio: [0.00028104 0.00087888 0.00142    0.00195734 0.00248608 0.00301084
 0.00353029 0.00404546 0.00455544 0.00506396 0.00556861 0.00607367
 0.00657582 0.0070768  0.00757645 0.00807415 0.00856913 0.00906119
 0.00955318 0.01004413 0.01053331 0.01102179 0.01150939 0.01199639
 0.01248221 0.01296686 0.01345101 0.01393265 0.01441363 0.01489328
 0.01537215 0.01585025 0.01632647 0.01680283 0.0172778  0.01775124
 0.01822385 0.0186964  0.01916809 0.01963862 0.02010712 0.02057548
 0.02104285 0.02150851 0.02197334 0.02243804 0.02290169 0.02336512
 0.02382819 0.02429063 0.02475258 0.02521355 0.02567404 0.02613387
 0.02659203 0.02704984 0.0275073  0.02796387 0.02841979 0.02887461
 0.02932858 0.02978191 0.03023468 0.030686   0.03113669 0.03158619
 0.03203552 0.03248344 0.03293078 0.0333774  0.03382347 0.03426889
 0.03471456 0.03515868 0.03560286 0.03604526 0.0364875  0.03692861
 0.03736944 0.03780958 0.03824924 0.03868747 0.03912536 0.03956192
 0.03999761 0.04043175 0.

In [13]:
from sklearn.decomposition import TruncatedSVD
# 3. TruncatedSVD로 차원 축소
n_components = 128  # 차원 수 (하이퍼파라미터, 튜닝 가능)
svd = TruncatedSVD(n_components=n_components, random_state=42)
User_svd = svd.fit_transform(user_matrix_sparse)  # 희소행렬에 직접 적용
User_svd

array([[ 0.20677533,  0.02200194, -0.03577066, ..., -0.13822727,
        -0.00630147,  0.09005696],
       [ 0.24543219, -0.0730484 , -0.03626692, ...,  0.16131968,
        -0.18823191,  0.13104842],
       [ 0.16120332,  0.05675215, -0.03175438, ...,  0.02408436,
        -0.0938067 , -0.11481933],
       ...,
       [ 0.1910876 , -0.03222204, -0.02283429, ..., -0.18869286,
        -0.04241162,  0.04925968],
       [ 0.31443312,  0.02579256, -0.13412332, ..., -0.01379606,
        -0.11407106, -0.15271984],
       [ 0.25706572, -0.07198695,  0.06109265, ..., -0.0169488 ,
        -0.02736267,  0.17208861]], shape=(28921, 128))

In [14]:
from sklearn.decomposition import TruncatedSVD
# 3. TruncatedSVD로 차원 축소
n_components = 128  # 차원 수 (하이퍼파라미터, 튜닝 가능)
svd = TruncatedSVD(n_components=n_components, random_state=42)
Item_svd = svd.fit_transform(item_matrix_sparse)  # 희소행렬에 직접 적용
Item_svd

array([[ 0.32455333, -0.05934555, -0.09428332, ..., -0.17057122,
         0.28296738,  0.0752143 ],
       [ 0.59772365, -0.35998032, -0.09187617, ...,  1.37694849,
         0.65537954, -0.05047051],
       [ 0.24113529,  0.66814995, -0.01575119, ...,  0.05103879,
        -0.00922005,  0.12538568],
       ...,
       [ 0.50528546,  0.02131371,  0.02007683, ...,  0.20476617,
        -0.27597645,  0.07366935],
       [ 0.55469145,  0.07886002, -0.19268081, ..., -0.3514155 ,
        -0.38178905,  0.37843658],
       [ 0.46729583, -0.04397579, -0.21501822, ...,  0.06471342,
        -0.22399251, -0.3780588 ]], shape=(4186, 128))

In [ ]:
import pandas as pd
import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import mean_squared_error
from scipy.sparse import csr_matrix
import warnings
warnings.filterwarnings('ignore')

# 2. User-Item Matrix 생성
user_item_matrix = df.pivot_table(index='user_idx', columns='product_idx', values='review_rating')
user_item_matrix = user_item_matrix.fillna(0)  # 결측값 0으로 채움
user_item_matrix_sparse = csr_matrix(user_item_matrix.values)  # 희소행렬로 변환

# 3. TruncatedSVD로 차원 축소
n_components = 100  # 차원 수 (하이퍼파라미터, 튜닝 가능)
svd = TruncatedSVD(n_components=n_components, random_state=42)
X_svd = svd.fit_transform(user_item_matrix_sparse)  # 희소행렬에 직접 적용

# Explained variance 확인
print(f"Explained variance ratio: {sum(svd.explained_variance_ratio_):.4f}")

# 4. 아이템 베이스 추천
# TruncatedSVD로 축소된 아이템 잠재 요인 행렬
item_factors = svd.components_.T  # 아이템 잠재 요인 (n_items × n_components)
item_similarity = cosine_similarity(item_factors)  # 아이템 간 유사도 행렬

def item_based_recommendation(user_id, user_item_matrix, item_similarity, top_n=10):
    user_ratings = user_item_matrix.loc[user_id].values
    scores = item_similarity.dot(user_ratings)  # 유사도 기반 스코어 계산
    top_items = np.argsort(scores)[::-1][:top_n]  # 상위 N개 아이템
    return top_items

# 5. 유저 베이스 추천
# 유저 잠재 요인 행렬 (X_svd: n_users × n_components)
user_similarity = cosine_similarity(X_svd)  # 유저 간 유사도 행렬

def user_based_recommendation(user_id, user_item_matrix, user_similarity, top_n=10):
    similar_users = np.argsort(user_similarity[user_id])[::-1][1:11]  # 상위 10명 유사 유저
    similar_users_ratings = user_item_matrix.iloc[similar_users].mean(axis=0)  # 평균 평점
    top_items = np.argsort(similar_users_ratings)[::-1][:top_n]  # 상위 N개 아이템
    return top_items

# 6. 성능 평가 (RMSE)
def evaluate_recommendation(user_item_matrix_sparse, train_ratio=0.8):
    # 희소행렬을 밀집행렬로 변환하지 않고 처리
    train_mask = np.random.rand(*user_item_matrix.shape) < train_ratio
    train_matrix = user_item_matrix_sparse.multiply(train_mask)  # 훈련 데이터
    test_matrix = user_item_matrix_sparse.multiply(~train_mask)  # 테스트 데이터

    # TruncatedSVD 적용
    svd = TruncatedSVD(n_components=n_components, random_state=42)
    train_svd = svd.fit_transform(train_matrix)
    item_factors = svd.components_.T
    item_sim = cosine_similarity(item_factors)

    # 아이템 베이스 예측
    pred_ratings = np.zeros_like(user_item_matrix.values)
    for user in range(user_item_matrix.shape[0]):
        user_ratings = train_matrix[user].toarray().flatten()
        scores = item_sim.dot(user_ratings)
        pred_ratings[user] = scores / (np.abs(item_sim).sum(axis=1) + 1e-10)

    # RMSE 계산
    mask = test_matrix.toarray() > 0
    if mask.sum() > 0:
        rmse = np.sqrt(mean_squared_error(test_matrix.toarray()[mask], pred_ratings[mask]))
        return rmse
    return np.nan

# 예시 실행
user_id = 0
print("Item-based recommendations:", item_based_recommendation(user_id, user_item_matrix, item_similarity))
print("User-based recommendations:", user_based_recommendation(user_id, user_item_matrix, user_similarity))
rmse = evaluate_recommendation(user_item_matrix_sparse)
print(f"RMSE: {rmse:.4f}")